# Site settings
title:       Castle of Ozdogan
subtitle:    "{thoughts and reviews}"
email:       ufukgozdogan@gmail.com
author:      Ufuk Ozdogan
description: |
 Is a DevOps Engineer and a Software Developer but also kind of a hardcore gamer some might probably say. Loves playing video games, watching movies/TV series and spending time with his family.

disclaimer: |
 None of the ideas expressed on this website are supported
 or endorsed in any manner by my employer.  
baseurl:     ""
url:         "https://ufukozdogan.github.io"
date_format: "%b %-d, %Y"
header_pages:
    # - about.md
    # - contact.html

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: 
google_tag_manager:
# Bing services
bing_verification:
azure_appinsights_key: 

# Optional features
show_categories     : true
animated            : false
show_related_posts  : true
show_post_footers   : true
show_social_icons   : true
ajaxify_contact_form: false
enable_mathjax      : false
extended_fonts      : true
enable_anchorjs     : false
# Preview image for social media aka og:image and twitter:image
post_preview_image  : false

# Facebook Page integration
# (for instant articles and other stuff)
fb_page             : false
fb_page_id:

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username         : ufukozdogan
reddit_username         : 
bitbucket_username      :
stackoverflow_id        :
twitter_username        : ufuk_ozdogan
skype_username          :
steam_nickname          :
google_plus_id          :
linkedin_username       : ufukozdogan
angellist_username      :
medium_id               :
bitcoin_url             :
paypal_url              :
flattr_button           :
telegram_username       :
vk_id                   :

# Show next and home buttons at the top of posts
show_page_navigation: true

# Show minutes for a post
show_page_minutes: true

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_email: true
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: true
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: false

text:
  category:
    label: 'Category'
    label-multi: 'Categories'
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'You might also like...'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
highlighter: rouge
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: /:year/:month/:day/:title
#permalink: pretty
paginate:  7
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - screenshot.png
  - vendor
